### PR TITLE
Reduce Firo storage requirement to 10GB

### PR DESCRIPTION
**Pull request by sygem**

### CODE REVIEW

**Review by TheTrunk — CHANGES_REQUESTED** [review]
I have checked our Firo explorer and it uses 64GB of storage. Granted it's an insight explorer with additional indexes but the size should not be decrease that much

**Comment by Cabecinha84** [comment]
https://firo.org/2021/12/19/mtp-stripping-live-on-firo.html

New full node fully synced used 4gb of blockchain data

**Review by TheTrunk — APPROVED** [review]
Oh wow that's so cooool

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Pull request merged**
